linha1 = str('---------------------------------------')
linha2 = str('|                                     |')
linha3 = str('|                                     |')
linha4 = str('|                                     |')
linha5 = str('|                                     |')
linha6 = str('|                                     |')
linha7 = str('---------------------------------------')
print(linha1)
print(linha2)
print(linha3)
print(linha4)
print(linha5)
print(linha6)
print(linha7)
